version: "3.9"

networks:
    laravel:
        name: laravel

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            - mysql
        container_name: nginx
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    mysql:
        image: mysql:8.0.27
        platform: linux/amd64
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        networks:
            - laravel

    composer:
        build:
            context: .
            dockerfile: composer.dockerfile
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
        networks:
            - laravel







